apiVersion: v1
kind: ServiceAccount
metadata:
  name: {{ include "greengrid.apiName" . }}
  labels:
    {{- include "greengrid.labels" . | nindent 4 }}
    app.kubernetes.io/component: telemetry-api
  {{- with .Values.serviceAccount.annotations.telemetryApi }}
  annotations: {{- toYaml . | nindent 4 }}
  {{- end }}
automountServiceAccountToken: false
---
apiVersion: v1
kind: ServiceAccount
metadata:
  name: {{ include "greengrid.generatorName" . }}
  labels:
    {{- include "greengrid.labels" . | nindent 4 }}
    app.kubernetes.io/component: telemetry-generator
  {{- with .Values.serviceAccount.annotations.telemetryGenerator }}
  annotations: {{- toYaml . | nindent 4 }}
  {{- end }}
automountServiceAccountToken: false

